name: Lint
on: [push, pull_request]
jobs:
  lint:
    name: Check python code using the official black action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            /*
            !*.parquet
          sparse-checkout-cone-mode: false
      - uses: psf/black@stable
        with:
          src: "."
          options: "--check --verbose --diff"