name: Tests and Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.11'
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install

      - name: Give execute permission to scripts
        run: chmod +x bin/lint bin/test

      - name: Run linting checks
        run: poetry run ./bin/lint
        env:
          CI: "true"

      - name: Run tests
        run: poetry run ./bin/test
        env:
          CI: "true"

      - name: Send coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # optional for public projects
          files: coverage.xml